### ISSUE TITLE
react-scripts get-schema url param

### ISSUE THREAD

**Issue by brysgo** [lpalmes/relay-modern-scripts#2]
The get-schema script works when invoked directly with node, but when I try to use it as a subcommand of react-scripts, it thinks the subcommand is the url parameter.

I'm still getting set up, but thanks for publishing your react scripts!

**Comment by lpalmes** [comment]
Hey, glad you like them, and let me know if you need any help using it, i could setup an example if you need one.

You are right, i will patch it, thanks!

**Comment by lpalmes** [comment]
v1.0.12 has fixed it, thanks for letting me know!
